name: Test spec

on: 
  push:
  schedule:
    - cron: '0 01 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        nim-version:
          - devel
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim-version }}

    - name: Test
      run: nimble tests
